---
# vars for Debian-based systems

postgresql_packages:
- postgresql
- postgresql-contrib

python_psycopg2_package: python3-psycopg2

postgresql_service: postgresql

postgresql_config_dir: "/etc/postgresql/{{ postgresql_version }}/main"
postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
