-ve three different --
# vars for RedHat-based systems

postgresql_packages:
- postgresql-server
- postgresql-contrib

python_psycopg2_package: python3-psycopg2

postgresql_service: postgresql

postgresql_config_dir: /var/lib/pgsql/data
postgresql_data_dir: /var/lib/pgsql/data
